import { City } from "./City";
import { PropertyCategory } from "./PropertyCategory";
import { PropertyType } from "./PropertyType";
import { User } from "./User";

export type Property = {
  id: number;
  propertyTypeId: number;
  propertyCategoryId: number;
  userId: number;
  cityId: number;
  featured: boolean;
  title: string;
  propertytagline:string;
  listingtype:string;
  description: string;
  featuredimage: string;
  imageNames: string;
  gallery: Array;
  bedRoomCount: number;
  bathRoomCount: number;
  baths: string;
  beds: string;
  kitchenRoomCount: number;
  parkingCount: number;
  additionalFeatures: string;
  price: number;
  priceString: string;
  currency: string;
  address: string;
  latitude: number;
  longitude: number;
  createdDate: Date;
  city: City;
  propertyCategory: PropertyCategory;
  propertyType: PropertyType;
  user: User;
  size: number;
  isLiked: boolean;
};
